@baseUrl = http://localhost:3000

### Try to login an unknow user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"unknown",
    "password":"admin"
}

### Login the default admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"Robin",
    "password":"1234"
}


### Create the user Joachim
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"Joachim",
    "email":"b.qi@gmail.com",
    "password":"1234"
}

### Login the user Joachim
# @name admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"Joachim",
    "password":"1234"
}

### delete user Joachim
DELETE {{baseUrl}}/auths/8
Authorization: {{admin.response.body.token}}





