@baseUrl = http://localhost:3000

### Login the user Joachim
# @name admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"Joachim",
    "password":"4321"
}

### Try to get all the categories
GET {{baseUrl}}/categories
Authorization: {{admin.response.body.token}}
