@baseUrl = http://localhost:3000

### Login the user Joachim
# @name admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"Robin",
    "password":"1234"
}

### Try to get one random question with category ENSE
GET {{baseUrl}}/questions/?category=ENSE


### Try to get one random question with an inexistant category
GET {{baseUrl}}/questions/?category=BASKETBALL

