@baseUrl = http://localhost:3000

### Try to get one random question with category ENSE
GET {{baseUrl}}/questions/?category=ENSE


### Try to get one random question with an inexistant category
GET {{baseUrl}}/questions/?category=BASKETBALL

